// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type DealspromoDocumentDataSlicesSlice = DealsAndPromosSlice;

/**
 * Content for DealsPromoPage documents
 */
interface DealspromoDocumentData {
  /**
   * Slice Zone field in *DealsPromoPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dealspromo.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DealspromoDocumentDataSlicesSlice> /**
   * Meta Title field in *DealsPromoPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dealspromo.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *DealsPromoPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dealspromo.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *DealsPromoPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dealspromo.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * DealsPromoPage document from Prismic
 *
 * - **API ID**: `dealspromo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DealspromoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DealspromoDocumentData>,
    "dealspromo",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | FooterSlice
  | MediaGallerySlice
  | NewRoomSlice
  | DealsPromoSlice
  | MarqueeSlice
  | HeroSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PromosDocumentDataSlicesSlice = PromosSlice;

/**
 * Content for PromosPage documents
 */
interface PromosDocumentData {
  /**
   * Slice Zone field in *PromosPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: promos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PromosDocumentDataSlicesSlice> /**
   * Meta Title field in *PromosPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: promos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *PromosPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: promos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PromosPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * PromosPage document from Prismic
 *
 * - **API ID**: `promos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PromosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PromosDocumentData>, "promos", Lang>;

export type AllDocumentTypes =
  | DealspromoDocument
  | HomepageDocument
  | PromosDocument;

/**
 * Item in *DealsAndPromos → Default → Primary → PromoCard*
 */
export interface DealsAndPromosSliceDefaultPrimaryPromocardItem {
  /**
   * PromoImage field in *DealsAndPromos → Default → Primary → PromoCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_and_promos.default.primary.promocard[].promoimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  promoimage: prismic.ImageField<never>;

  /**
   * Link field in *DealsAndPromos → Default → Primary → PromoCard*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_and_promos.default.primary.promocard[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *DealsAndPromos → Default → Primary*
 */
export interface DealsAndPromosSliceDefaultPrimary {
  /**
   * Heading field in *DealsAndPromos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_and_promos.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * PromoCard field in *DealsAndPromos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_and_promos.default.primary.promocard[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  promocard: prismic.GroupField<
    Simplify<DealsAndPromosSliceDefaultPrimaryPromocardItem>
  >;

  /**
   * BackButton field in *DealsAndPromos → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_and_promos.default.primary.backbutton
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  backbutton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for DealsAndPromos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DealsAndPromosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DealsAndPromosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DealsAndPromos*
 */
type DealsAndPromosSliceVariation = DealsAndPromosSliceDefault;

/**
 * DealsAndPromos Shared Slice
 *
 * - **API ID**: `deals_and_promos`
 * - **Description**: DealsAndPromos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DealsAndPromosSlice = prismic.SharedSlice<
  "deals_and_promos",
  DealsAndPromosSliceVariation
>;

/**
 * Item in *DealsPromo → Default → Primary → Card*
 */
export interface DealsPromoSliceDefaultPrimaryCardItem {
  /**
   * Image field in *DealsPromo → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_promo.default.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *DealsPromo → Default → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_promo.default.primary.card[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Body field in *DealsPromo → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_promo.default.primary.card[].body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;
}

/**
 * Primary content in *DealsPromo → Default → Primary*
 */
export interface DealsPromoSliceDefaultPrimary {
  /**
   * Card field in *DealsPromo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_promo.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<DealsPromoSliceDefaultPrimaryCardItem>>;

  /**
   * Heading field in *DealsPromo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_promo.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Button field in *DealsPromo → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: deals_promo.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for DealsPromo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DealsPromoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DealsPromoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DealsPromo*
 */
type DealsPromoSliceVariation = DealsPromoSliceDefault;

/**
 * DealsPromo Shared Slice
 *
 * - **API ID**: `deals_promo`
 * - **Description**: DealsPromo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DealsPromoSlice = prismic.SharedSlice<
  "deals_promo",
  DealsPromoSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Carousel*
 */
export interface HeroSliceDefaultPrimaryCarouselItem {
  /**
   * Images field in *Hero → Default → Primary → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[].images
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  images: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Carousel field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryCarouselItem>>;

  /**
   * LogoImage field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logoimage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logoimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Marquee → Default → Primary → phrases*
 */
export interface MarqueeSliceDefaultPrimaryPhrasesItem {
  /**
   * Text field in *Marquee → Default → Primary → phrases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.phrases[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * phrases field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.phrases[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  phrases: prismic.GroupField<Simplify<MarqueeSliceDefaultPrimaryPhrasesItem>>;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Primary content in *MediaGallery → Default → Primary*
 */
export interface MediaGallerySliceDefaultPrimary {
  /**
   * Heading field in *MediaGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_gallery.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Button field in *MediaGallery → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media_gallery.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Youtube Video Id field in *MediaGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_gallery.default.primary.youtube_video_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  youtube_video_id: prismic.KeyTextField;
}

/**
 * Default variation for MediaGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MediaGallery*
 */
type MediaGallerySliceVariation = MediaGallerySliceDefault;

/**
 * MediaGallery Shared Slice
 *
 * - **API ID**: `media_gallery`
 * - **Description**: MediaGallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGallerySlice = prismic.SharedSlice<
  "media_gallery",
  MediaGallerySliceVariation
>;

/**
 * Item in *Newsroom → Default → Primary → Card*
 */
export interface NewRoomSliceDefaultPrimaryCardItem {
  /**
   * Image field in *Newsroom → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: new_room.default.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Newsroom → Default → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: new_room.default.primary.card[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Newsroom → Default → Primary*
 */
export interface NewRoomSliceDefaultPrimary {
  /**
   * Card field in *Newsroom → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: new_room.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<NewRoomSliceDefaultPrimaryCardItem>>;

  /**
   * Heading field in *Newsroom → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: new_room.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Button field in *Newsroom → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: new_room.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Newsroom Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewRoomSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewRoomSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsroom*
 */
type NewRoomSliceVariation = NewRoomSliceDefault;

/**
 * Newsroom Shared Slice
 *
 * - **API ID**: `new_room`
 * - **Description**: NewRoom
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewRoomSlice = prismic.SharedSlice<
  "new_room",
  NewRoomSliceVariation
>;

/**
 * Default variation for Promos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PromosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Promos*
 */
type PromosSliceVariation = PromosSliceDefault;

/**
 * Promos Shared Slice
 *
 * - **API ID**: `promos`
 * - **Description**: Promos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PromosSlice = prismic.SharedSlice<"promos", PromosSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DealspromoDocument,
      DealspromoDocumentData,
      DealspromoDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PromosDocument,
      PromosDocumentData,
      PromosDocumentDataSlicesSlice,
      AllDocumentTypes,
      DealsAndPromosSlice,
      DealsAndPromosSliceDefaultPrimaryPromocardItem,
      DealsAndPromosSliceDefaultPrimary,
      DealsAndPromosSliceVariation,
      DealsAndPromosSliceDefault,
      DealsPromoSlice,
      DealsPromoSliceDefaultPrimaryCardItem,
      DealsPromoSliceDefaultPrimary,
      DealsPromoSliceVariation,
      DealsPromoSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryCarouselItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MarqueeSlice,
      MarqueeSliceDefaultPrimaryPhrasesItem,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      MediaGallerySlice,
      MediaGallerySliceDefaultPrimary,
      MediaGallerySliceVariation,
      MediaGallerySliceDefault,
      NewRoomSlice,
      NewRoomSliceDefaultPrimaryCardItem,
      NewRoomSliceDefaultPrimary,
      NewRoomSliceVariation,
      NewRoomSliceDefault,
      PromosSlice,
      PromosSliceVariation,
      PromosSliceDefault,
    };
  }
}
