// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  deals_and_promos: dynamic(() => import("./DealsAndPromos")),
  deals_promo: dynamic(() => import("./DealsPromo")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  media_gallery: dynamic(() => import("./MediaGallery")),
  new_room: dynamic(() => import("./Newsroom")),
  promos: dynamic(() => import("./Promos")),
};
